version: "3.9"

services:
  app:
    build: .
    ports:
      - "5050:5000"
    volumes:
      - ./app/images:/app/images
      - ./app/uploads:/app/uploads
      - ./receipts.db:/app/receipts.db
    env_file:
      - .env
    depends_on:
      - waha

  waha:
    image: devlikeapro/waha:chrome-2025.9.8
    ports:
      - "8080:3000"
    environment:
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
    volumes:
      - ./waha_data:/app/data
