version: '3.8'

services:
  app:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./app/images:/app/images
      - ./app/uploads:/app/uploads
      - ./app/logs:/app/logs
    env_file:
      - .env
    depends_on:
      - waha  # If you have a WAHA service
    restart: unless-stopped

  # Other services like waha...