version: "3.9"

services:
  waha:
    image: devlikeapro/waha:latest  # Use a specific tag if preferred, e.g., :2024.10
    container_name: waha
    ports:
      - "3000:3000"  # Expose WAHA's API if you need external access (e.g., for manual testing)
    volumes:
      - ./waha_data:/app/data  # Persistent storage for WAHA sessions and data
    environment:
      - WAHA_ENGINE=NOWEB  # Or VENOM/others; configure based on your needs
      - WAHA_WEBHOOK_SECRET=${WEBHOOK_SECRET}  # Pull from .env to match your app's secret
      # Add other WAHA env vars as needed, e.g., for webhook URL
    restart: unless-stopped 

  app:
    build: .
    container_name: app
    ports:
      - "5050:5050"
    volumes:
      - ./app:/app          # App code
      - ./sessions:/app/sessions  # Persistent session storage
    env_file:
      - .env
    environment:
      - FLASK_APP=main:app      # Tell Flask to use main.py's 'app' variable
      - FLASK_ENV=development   # Optional, for auto-reload
    depends_on:
      - waha
    command: flask run --host=0.0.0.0 --port=5050
    restart: unless-stopped
